import express from "express";
import { userRoute } from "./userAuth.js";
import { sellerRoute } from "./sellerRoutes.js";
import { adminRouter } from "./adminRoute.js";
import { productRoute } from "./productRoute.js";
import { cartRouter } from "./cartRoute.js";
import { orderRouter } from "./orderRoute.js";
export const allRoutes = express.Router();
allRoutes.use("/auth/user", userRoute);
allRoutes.use("/store", sellerRoute);
allRoutes.use("/admin", adminRouter);
allRoutes.use("/product", productRoute);
allRoutes.use("/cart", cartRouter);
allRoutes.use("/order", orderRouter);
